### PR TITLE
Update index.md 16748

### PR DESCRIPTION
**Pull request by Picklze1**
Changes
- Sadie is now programer

### CODE REVIEW

**Review by olivia-banks — CHANGES_REQUESTED** [review]

**Review by Picklze1 — COMMENTED** [review]
fantastic

**Review by olivia-banks — APPROVED** [review]

**Review by olivia-banks — CHANGES_REQUESTED** [review]
Remove 'cool'.

**Review by RZW-13 — CHANGES_REQUESTED** [review]
:)

**Review by olivia-banks — APPROVED** [review]
Wonderous.

**Pull request merged**
